# Generated by Django 3.0.2 on 2020-01-28 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parks', '0002_auto_20200128_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='park',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='parks.Park'),
        ),
    ]
